# Site settings
title: Lucia Urcelay
author: Lucia Urcelay
description: "💐"
baseurl: ""
url: "https://luciaurcelay.github.io"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-113168316-1
google_tag_manager:
# Bing services
bing_verification:

# Optional features
show_post_footers: True
show_contact: True
show_social_icons: false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: luciaurcelay
stackoverflow_id:
twitter_username: Lucia_Urcelay
linkedin_username: luciaurcelay

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: pretty
paginate: 12
paginate_path: "/publications/:num/"
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true
